# Graphs

1. Scales should start at zero! Otherwise ratios are misleading.
2. Objects whose area or volume are meant to show a statistic can be deceptive. People will make "linear comparisons" but the area or volume do not grow linearly.


In [25]:
import numpy as np

import rich
from rich.console import Console
from packaging.version import Version

In [2]:
console = Console(
    width=80,
    color_system="truecolor",
    soft_wrap=True,
    emoji=True,
    log_time=True,
    log_path=True
)

In [3]:
data = [0, 1, 2, 3, 0, 1, 2, 0, 1, 0, 5, -1]
np.bincount(data)

ValueError: 'list' argument must have no negative elements

In [4]:
data = [0, 1, 2, 3, 0, 1, 2, 0, 1, 0, 5]
np.bincount(data)

array([4, 3, 2, 1, 0, 1])

In [5]:
# amax is an alias for max.
# the thing with bincount is that since it assumes that entries are non-negative, then its size
# should match the max + 1 (because python counts from 0).
np.amax(data), np.bincount(data).size == np.max(data)+1

(np.int64(5), np.True_)

In [6]:
np.histogram(data, bins=6, density=False)

(array([4, 3, 2, 1, 0, 1]),
 array([0.        , 0.83333333, 1.66666667, 2.5       , 3.33333333,
        4.16666667, 5.        ]))

In [7]:
pkgs = {
    'numpy': '2.1.2',
    'scipy': '1.14.1',
    'matplotlib': '3.9.2',
    'sklearn': '1.5.2',
    'pandas': '2.2.3'


In [32]:
for p in pkgs.keys():
    imported = __import__(p)
    actual = pkgs[imported.__name__]
    if Version(actual) > Version(imported.__version__):
        console.print(":beetle: [bold rgb(255,20,147)]Go update your packages! [/bold rgb(255,20,147)]")
        console.print(f'your version of {imported.__name__} is {imported.__version__} but we\'d like you to have {actual} at least')

In [33]:
console.print(pkgs)

{
    'numpy': '2.1.2',
    'scipy': '1.14.1',
    'matplotlib': '3.9.2',
    'sklearn': '1.5.2',
    'pandas': '2.2.3'
}