In [4]:
import numpy as np
import pandas as pd

# Exploring Covariance

In [5]:
s = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

df = pd.read_csv(s, header=None, encoding='utf-8')
df.head()

0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [8]:
# select setosa and versicolor
y = df.iloc[0:10, 4].values
y = np.where(y == 'Iris-setosa', 0, 1)

# extract sepal length and petal length
X = df.iloc[0:10, [0, 2]].values

In [9]:
X, y

(array([[5.1, 1.4],
        [4.9, 1.4],
        [4.7, 1.3],
        [4.6, 1.5],
        [5. , 1.4],
        [5.4, 1.7],
        [4.6, 1.4],
        [5. , 1.5],
        [4.4, 1.4],
        [4.9, 1.5]]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))

In [14]:
X_train = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
    ]
)

X_train, X_train.T

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 4],
        [2, 5],
        [3, 6]]))

In [15]:
np.cov(X_train)

array([[1., 1.],
       [1., 1.]])

In [17]:
# The numpy.cov docs say:
# Each row of m represents a variable, and each column a single observation of all those variables.
np.cov(X_train.T)

array([[4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5]])