In [1]:
import numpy as np

In [2]:
x = [0, 2, 3]
y = [1, 2, 4]

In [3]:
n = len(x)
n

3

In [4]:
v = np.zeros([n, n])
v

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
v[:, 0] = y
v

array([[1., 0., 0.],
       [2., 0., 0.],
       [4., 0., 0.]])

In [6]:
for i in range(1,n):
    print(f"i = {i}")
    for j in range(0, n-i):
        print(f"j = {j}")
        
        x_left  = x[j+i]
        x_right = x[j]
        print(f"\tx_left = {x_left} and x_right = {x_right}")

        f_left  = v[j+1,i-1]
        f_right = v[j,  i-1]
        print(f"\tf_left = {f_left} and f_right = {f_right}")

        v[j, i] = (f_left - f_right) / (x_left - x_right)

i = 1
j = 0
	x_left = 2 and x_right = 0
	f_left = 2.0 and f_right = 1.0
j = 1
	x_left = 3 and x_right = 2
	f_left = 4.0 and f_right = 2.0
i = 2
j = 0
	x_left = 3 and x_right = 0
	f_left = 2.0 and f_right = 0.5


In [7]:
v

array([[1. , 0.5, 0.5],
       [2. , 2. , 0. ],
       [4. , 0. , 0. ]])

In [8]:
v[0,:]

array([1. , 0.5, 0.5])

In [9]:
import sys
sys.path.append("..")
from numa.horner import horner_simple_polynomial_evaluation

In [10]:
print(v[0,:])
horner_simple_polynomial_evaluation(v[0,:], 0, b=x) 

[1.  0.5 0.5]
first coefficient: 0.5
0.5 + x*0.5
1.0 + x*-0.5


1.0

In [11]:
print(v[0,:])
horner_simple_polynomial_evaluation(v[0,:], 0)

[1.  0.5 0.5]
first coefficient: 0.5
0.5 + x*0.5
1.0 + x*0.5


1.0

In [12]:
# P_2 (2) = 2.
horner_simple_polynomial_evaluation(v[0,:], 2, b=x)

first coefficient: 0.5
0.5 + x*0.5
1.0 + x*0.5


2.0

In [14]:
# P_2 (3) = 4.
horner_simple_polynomial_evaluation(v[0,:], 3, b=x)

first coefficient: 0.5
0.5 + x*0.5
1.0 + x*1.0


4.0